### PR TITLE
fix(op-node): alchemy as rpc node for opbnb

### PR DESCRIPTION
**Pull request by Eoous**
### Description

Fix: #228 

### Changes

When using alchemy as `L1_RPC_KIND`:

- fallback to `EthGetTransactionReceiptBatch
- check error message

### CODE REVIEW

**Comment by welkin22** [comment]
@Eoous Hi, please fix the broken unit tests first. I will pull the code and test locally to see if it fixes the alchemy issue.

**Comment by Eoous** [comment]
@welkin22 How about deleting the test cases for alchemy? Currently alchemy only support standard methods and no need to do fallback test

**Comment by welkin22** [comment]
> @welkin22 How about deleting the test cases for alchemy? Currently alchemy only support standard methods and no need to do fallback test
> 
> In addition there're some timers for response required delay, they would print warn or error if use third-party service

Yes, these test cases are no longer needed.

**Review by welkin22 — APPROVED** [review]
LGTM

**Comment by owen-reorg** [comment]
We'll put this pull request on hold as we're communicating with Alchemy to add support for the missing APIs in their BSC endpoint.

**Comment by Eoous** [comment]
> We'll put this pull request on hold as we're communicating with Alchemy to add support for the missing APIs in their BSC endpoint.

That's great

**Pull request closed without merging**
